controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - base_twist
      - shoulder
      - elbow
      - wrist
  - name: fake_eef_group_controller
    type: $(arg fake_execution_type)
    joints:
      - left_grip
      - right_grip
  - name: fake_steering_group_controller
    type: $(arg fake_execution_type)
    joints:
      - back_left_steer
      - back_right_steer
      - front_left_steer
      - front_right_steer
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: default
  - group: eef_group
    pose: open
  - group: steering_group
    pose: straight