controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - base_twist
      - shoulder
      - elbow
      - wrist
  - name: fake_eef_group_controller
    type: $(arg fake_execution_type)
    joints:
      - left_grip
      - right_grip
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: default
  - group: eef_group
    pose: open