arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_twist
    - shoulder
    - elbow
    - wrist
  gains:
    base_twist:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_grip
    - right_grip
  gains:
    left_grip:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_grip:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
steering_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - back_left_steer
    - back_right_steer
    - front_left_steer
    - front_right_steer
  gains:
    back_left_steer:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    back_right_steer:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    front_left_steer:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    front_right_steer:
      p: 100
      d: 1
      i: 1
      i_clamp: 1