controller_list:
  - name: arm_comtroller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - base_to_L1
      - L1_to_L2
      - L2_to_L3
      - L3_to_L4
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - L4_to_L5_1_A